### PR TITLE
Fix image and profile data re-rendering

### LINKED ISSUE #59: Image upload re-render bug
State is not updating after uploading a picture, again
The branch is `fix-image-2`

### LINKED ISSUE #60: Profile data re-render bug

### PR DESCRIPTION
**Pull request by ajtran303**
#### What's this PR do?

Fixes re-render bugs

This PR can also be considered a refactor!

#### Where should the reviewer start?

`actions.js`

#### How should this be manually tested?

- Pull down the branch
- in `api`, run `npm db:reset`
- start the app
- start postico, go to user table
- Log in as user
- Upload photo, then all other information
- *IMPORTANT* click the save button, don't use the return key
- refresh the table view in postico

#### Any background context you want to provide?

After updating the info *DO NOT REFRESH THE PAGE*
Instead: flip to a different tab (subscription, crate) and then back to profile
Log out and log back in

#### What are the relevant tickets?

closes #59 
closes #60

### CODE REVIEW

**Review by dtsehl — APPROVED** [review]

File: code/web/src/modules/user/ProfilePicture.js [hunk 1]
```diff
@@ -56,8 +55,7 @@ class ProfilePicture extends Component {
     }
 
     saveChanges = () => {
-      this.props.updateUser(this.state, this.props.user.details.id)
-      this.props.getUser(this.props.user.details.id)
+      this.props.updateProfileData(this.state)
```
Comment (kathytbui) [inline code/web/src/modules/user/ProfilePicture.js:58]: Nice resuse of Leigh's function.

File: code/web/src/modules/user/ProfilePicture.js [hunk 2]
```diff
@@ -6,26 +6,24 @@ import { upload, messageShow, messageHide } from '../common/api/actions'
...
 class ProfilePicture extends Component {
   constructor() {
-    super() 
+    super()
     this.state = {
-      imgURL: '',
-      name: '',
-      email: '',
+      id: '',
+      image: '',
```
Comment (carlymclift) [inline code/web/src/modules/user/ProfilePicture.js:16]: Thank you removing email and name from here, since they weren't being used

**Review by kathytbui — APPROVED** [review]

**Review by carlymclift — APPROVED** [review]
Great work. I'm glad we were able to cut down on and delete some unnecessary code
